spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    username: manageritdrive@gmail.com
    password: oxfyosjjchbcawem
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        mail: DEBUG

base:
  url: https://${NGROK_ID}.ngrok-free.app

dropbox:
  api:
    host: https://api.dropboxapi.com/2/
    token: Bearer