### Вход

POST  localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=user@mail.com&password=Qwerty007!

### Добавление курса

POST http://localhost:8080/api/courses
Content-Type: application/json

{
  "title": "Курс QA",
  "beginDate": "2023-02-02",
  "endDate": "2024-02-02",
  "description": "Курс по QA",
  "price": 150.0
}

### Получение курсов

GET http://localhost:8080/api/courses

### Получение одного курса

GET http://localhost:8080/api/courses/2

### Регистрация пользователя

POST localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "sidikov.marsel@gmail.com",
  "password": "Qwerty007!"
}

### Добавление урока в курс

POST localhost:8080/api/courses/1/lessons
Content-Type: application/json

{
  "name": null,
  "startTime": "09:30",
  "finishTime": "13:00",
  "dayOfWeek": "MONDAY"
}

### Добавление урока в курс

POST localhost:8080/api/courses/1/lessons
Content-Type: application/json

{
  "name": "SQL",
  "startTime": "13:00",
  "finishTime": "16:00",
  "dayOfWeek": "FRIDAY"
}

### Добавление существующего урока в курс

POST localhost:8080/api/courses/1/lessons
Content-Type: application/json

{
  "existsLessonId": 2
}

### Получение всех уроков курса

GET localhost:8080/api/courses/1/lessons

### Удаление урока из курса

DELETE localhost:8080/api/courses/1/lessons/2

### Обновление урока в курсе

PUT localhost:8080/api/courses/1/lessons/3
Content-Type: application/json

{
  "name": "SQL",
  "startTime": "18:30",
  "finishTime": "22:00"
}

### Добавление студента в курс

POST localhost:8080/api/courses/1/students
Content-Type: application/json

{
  "userId": 4
}

### Получение всех студентов курса

GET localhost:8080/api/courses/1/students