### Добавление курса

POST http://localhost:8080/api/courses
Content-Type: application/json

{
  "title": "Новый курс",
  "beginDate": "2022-02-02",
  "endDate": "2023-02-02",
  "description": "Описание нового курса",
  "price": 100.0
}

### Получение курсов

GET http://localhost:8080/api/courses